### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ghost** [Anubiella/teacozy#4]
Grade: Meets Expectations

Good job overall! You can add alt attributes and delete any extra spacing. Your code's syntax is good. As a challenge, consider adding a drop down menu and expanding the webiste by adding more pages, I think you're ready for it!

**Comment by Anubiella** [comment]
Thanks a lot sir,

I know a have a loooot of things to learn but I'm patient enough to walk through it.

I will cope with the issues you've summerized above immediately, thanks again!

Have a nice day!
Lorenzo
